### ISSUE TITLE
How to reset contentInset.Top

### ISSUE THREAD

**Issue by akinLiu** [sergigracia/KoaPullToRefresh#2]
I found the default contentInset.Top is 2 of my custom tableView after I use `KoaPullToRefresh` ,How to set the Default contentInset.Top value to 0?

**Comment by akinLiu** [comment]
sorry It's my negligence in the method `addPullToRefreshWithActionHandler:(void (^)(void))actionHandler
                      withBackgroundColor:(UIColor *)customBackgroundColor
            withPullToRefreshHeightShowed:(CGFloat)pullToRefreshHeightShowed` I give a wrong `pullToRefreshHeightShowed` that I don't expect

**Comment by sergigracia** [comment]
:+1:
