### ISSUE TITLE
iOS7 + UINavigationBar compatibility issue

### ISSUE THREAD

**Issue by alexiscreuzot** [sergigracia/KoaPullToRefresh#6]
Current version is not compatible with iOS7, UITableView get positioned behind UINavigationBar.

**Comment by jstart** [comment]
:+1: Any idea why this is happening?  Something to do with the transparent nav bars in iOS7?  SVPullToRefresh is doing this same behavior.

**Comment by jstart** [comment]
Spoke too soon, seems this solves the problem:
http://stackoverflow.com/questions/17074365/status-bar-and-navigation-bar-appear-over-my-views-bounds-in-ios-7
Putting the below code in viewDidLoad seems to resolve the issue

```
if ([self respondsToSelector:@selector(edgesForExtendedLayout)])
    self.edgesForExtendedLayout = UIRectEdgeNone;
```

**Comment by alexiscreuzot** [comment]
Woops, I forgot I had open an issue for this. Yes, putting `edgesForExtendedLayout` to `UIRectEdgeNone` did the trick for me too ! Thanks ;)
